Swatinem/rollup-plugin-dts

- src/DeclarationScope.ts
- src/__tests__/testcases/generics/expected.d.ts
- src/__tests__/testcases/generics/index.ts
- src/__tests__/testcases/type-constructor/expected.d.ts
- src/__tests__/testcases/type-constructor/index.ts
- src/__tests__/testcases/type-function/expected.d.ts
- src/__tests__/testcases/type-function/index.ts
- src/__tests__/testcases/type-nodes/expected.d.ts
- src/__tests__/testcases/type-nodes/index.ts
This adds support for:
* function types, e.g. `type Fn = (a: A) => B`
* constructor types, e.g. `type Ctor = new (a: A) => B`
* type predicates, e.g. `(a: any) => a is A`
> Support more types

- src/Transformer.ts
- src/__tests__/testcases/import-no-import-clause/bar.ts
- src/__tests__/testcases/import-no-import-clause/expected.d.ts
- src/__tests__/testcases/import-no-import-clause/index.ts
I'd love to use this plugin (great work!) but I need to import some polyfills into my bundle (ex: `import 'core-js';`).
This PR adds support for this pattern.
> Support imports without name

- src/DeclarationScope.ts
- src/__tests__/testcases/generics/expected.d.ts
- src/__tests__/testcases/generics/index.ts
- src/__tests__/testcases/overrides/index.ts
- src/__tests__/testcases/shadowing/expected.d.ts
- src/__tests__/testcases/shadowing/exports.ts
- src/__tests__/testcases/shadowing/index.ts
- src/__tests__/testcases/type-this/expected.d.ts
- src/__tests__/testcases/type-this/index.ts
```typescript
interface Foo<T> {
foo: T;
}
interface Bar {}
interface FooBar extends Foo<Bar> {} // <<<
```
```typescript
interface Foo {
foo: string;
}
declare class FooBuilder {
foo(foo: string): this; // <<<
build(): Foo;
}
```
**Drive-by fix:** the "implementation" for the class method with overrides had an incorrect type. This doesn't affect the generated type definitions (since the implementation's signature is always removed), but I thought it's better to give it a more "realistic" type. 😛
> Support even more types

- src/compiler.ts
The build is failing with the error `rollup-plugin-dts: Couldn't find tsconfig file` when a project directory contains dots.
1. Place `rollup.config.js` with the following configuration:
```
import { dts } from 'rollup-plugin-dts';
export default {
input: 'src/index.ts',
output: [
{
file: 'dist/index.d.ts',
format: 'esm',
},
],
plugins: [ dts() ],
};
```
2. Rename your TypeScript project directory to contain at least one dot (like `my-library.js`).
3. Run `rollup -c rollup.config.js`.
Build succeeds.
Build fails with the error `rollup-plugin-dts: Couldn't find tsconfig file`.
Due to [this code](https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/compiler.ts#L48), the plugin uses directory name as the `tsconfig` file name and then fails to find a file named `my-library.js`. …
> fix tsconfig lookup when projects directory contains dots

- src/index.ts
This compiles ".ts" modules into ".d.ts" modules in-memory and forwards them to Rollup.
This removes the need for intermediate files.
Fixes #31
> feat: support ".ts" modules

- src/DeclarationScope.ts
- tests/testcases/type-simple/expected.d.ts
- tests/testcases/type-simple/index.ts
[Supported since TypeScript 3.2](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint)
> Add support for bigints

- src/index.ts
Hi, for my project I need set up `baseUrl` for TypeScript, so I added `compilerOptions` to handle it. 
I'm using absolute path, for example I have file `src/components/Button.tsx` and elsewhere I use import `import Button from 'components/Button'`.
If you find out it as valuable for you, plese look at the PR ;)
If I did something wrong, let me know, thank you (and for your work).
> Add TS compiler options to plugin options

- src/Transformer.ts
when used rollup >= 2.9, (2.8 works well), TypeError cause
debug to locate here. 
i will report to rollup too.
> ExportAllDeclaration without exported should be null to avoid breaking rollup >= 2.9.x

- src/NamespaceFixer.ts
- tests/testcases/re-export-namespace-multiple/defs.d.ts
- tests/testcases/re-export-namespace-multiple/expected.d.ts
- tests/testcases/re-export-namespace/expected.d.ts
- tests/testcases/re-export-namespace/namespace.d.ts
namespace fixer treats interface as type and type as const. It should treat them same way.
> fix: support of type aliases in namespaces

- src/index.ts
In case you think my proposed solution to issue #131 is a good idea, here's an implementation.
> Suppress circular dependency warnings by default

- src/transform/NamespaceFixer.ts
Sorry the PR doesn't come with a test case. I just came across a situation in this line:
```
const { type, generics } = itemTypes[localName]!
```
where  `itemTypes[localName]` is undefined. The destructuring statement throws and the build fails. I haven't been able to produce a repro as I'm time-constrained at the moment. However, this patch seems to fix the issue and it also matches the correct type signature by removing the postfix `!`.
> Account for situation where itemTypes[localName] is undefined

- src/transform/NamespaceFixer.ts
- tests/testcases/namespace-keyword-exports/expected.d.ts
- tests/testcases/namespace-keyword-exports/foo.d.ts
- tests/testcases/namespace-keyword-exports/index.d.ts
Related issue: #149
As this may be a `.ts` input-file-only issue, I wasn't sure how to include tests for this.
If this is deemed unsupported, feel free to close this PR.
> fix: support keyword export names in namespace

- src/index.ts
I have dir tree:
```shell
├── a.ts
├── b-dir
├── b.ts
└── c.ts
```
use tsup and make config as: 
```ts
import { defineConfig } from "tsup";
export default defineConfig({
entryPoints: ["a.ts", "./b-dir/b.ts"],
dts: true,
clean: true,
});
```
to compile all ts file, and expect to get `dts` file.
```shell
pnpm tsup
```
I got `dist` dir, and the tree looks like this:
```shell
├── dist
├── a.d.ts
├── a.js
├── b-dir
└── b.d.ts
```
File `b.d.ts` was written at dist  dir. But expected that `b.d.ts` should be `b-dir/`.
Just like:
```shell
├── dist
├── a.d.ts
├── a.js
└── b-dir
├── b.d.ts
└── b.js
```
Only the `Array` type `inputConfig.input` will Cause this situation.
When I make `inputConfig.input` be:
```js
{
a: "a.ts", 
"b-dir/b": "./b-dir/b.ts"
}
```
the tree:
```shell
├── dist
├── a.d.ts
├── …
```
> fix: *.d.ts always be writed  in root dir

- src/program.ts
Fix: https://github.com/Swatinem/rollup-plugin-dts/issues/179
> chore: allow override compiler options

- src/transform/index.ts
- src/transform/preprocess.ts
- tests/testcases/reference-path-remapping/expected.d.ts
- tests/testcases/reference-path-remapping/index.d.ts
- tests/testcases/reference-path-remapping/ns-api.d.ts
- tests/testcases/reference-path-remapping/sub/api2.d.ts
- tests/testcases/reference-path-remapping/sub/ns-api2.d.ts
PR to fix the [triple-slash reference path](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-path-), not correctly bundled in the output file.
For example:
`index.d.ts`:
```ts
/// <reference path="./lib-global-ns.d.ts" />
export * from "./sub/lib-es.ts";
```
`lib-es.ts`:
```ts
/// <reference path="./lib-global-ns-2.d.ts" />
// [...]
```
should result in a bundled file with all the references at the top, with correct relative paths:
```ts
/// <reference path="./lib-global-ns.d.ts" />
/// <reference path="./sub/lib-global-ns-2.d.ts" />
// [...]
```
The triple-slash reference path syntax can still be used in ES-module declarations files. For example, it can be used in mixed projects that are still using global namespaces. In that case, migrating a …
> Support for reference path directives

- src/transform/index.ts
- src/transform/preprocess.ts
- tests/testcases/reference-path-remapping-should-not-touch-absolute-path/expected.d.ts
- tests/testcases/reference-path-remapping-should-not-touch-absolute-path/index.d.ts
Hi 👋 
First of all thank you for the great package 🙃 , while using it I've noticed triple slash references are remapped to the main file, which is great.
However, while re-mapping references, IMO the remapping should handle _only_ relative paths, and leave as-is absolute paths.
Another option is to respect [noResolve](https://www.typescriptlang.org/tsconfig#noResolve) TS `compilerOptions` flag maybe?
> Reference remapping should not touch absolute path

- src/index.ts
- src/program.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/common.d.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/expected.d.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/meta.js
- tests/testcases/multiple-entries-multiple-tsconfigs/packages/packi/index.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/packages/packi/src/entries/entry-a.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/packages/packi/src/entries/entry-b.ts
- tests/testcases/multiple-entries-multiple-tsconfigs/packages/packi/tsconfig.json
- tests/testcases/multiple-entries-multiple-tsconfigs/tsconfig.json
- tests/utils.ts
Now caching `tsconfig.json` per directory. Related: https://github.com/Swatinem/rollup-plugin-dts/pull/238#issuecomment-1368398657
Other improvements:
- added tests for #238
- fail tests on `console.error`
- only resolve custom `compilerOptions` if needed i.e. if `tsconfig` option was provided
- logging for caching behaviour when `DTS_LOG_CACHE` env var is set
You can see tests failing with and without the last commit.
With this change, `getCompilerOptions` is only called a handful of times:
```
⚙️  Creating dts bundle...
getCompilerOptions()
[cache] miss /___/braid-design-system/packages/braid-design-system/src
[cache] tsconfig { <snip> }
[cache] /___/braid-design-system/packages/braid-design-system/src
[cache] up /___/braid-design-system/packages/braid-design-system
getCompilerOptions() …
```
> Cache `tsconfig.json` once resolved

- src/index.ts
- tests/testcases/inline-external-node-next-module/expected.d.ts
- tests/testcases/inline-external-node-next-module/index.d.ts
- tests/testcases/inline-external-node-next-module/meta.js
- tests/testcases/inline-external-node-next-module/node_modules/package-a/package.json
- tests/testcases/inline-external-node-next-module/node_modules/package-a/types/file.d.ts
While trying to inline external dependencies, I saw that a TypeScript function was used that did not respect the moduleResolution of the config. It is changed to a similar functions that does respect the moduleResolution. There is also a test added that verifies that it works for NodeNext/Node16 for moduleResolution.
> Allow to use same resolve method as tsconfig (e.g. NodeNext)

- package.json
- rollup.config.ts
close https://github.com/Swatinem/rollup-plugin-dts/issues/210
> fix: export both cjs and esm types

- .github/workflows/ci.yml
- package.json
lower the `node` requirements to `>=16`,reduce install fail caused by the `engine-strict = true` configuration item in `.npmrc`. #282
> chore(deps): lower the node requirements to >=16

- src/transform/DeclarationScope.ts
- tests/testcases/type-typeof-this/expected.d.ts
- tests/testcases/type-typeof-this/index.d.ts
> fix: `typeof this` usage in classes should not alias to `typeof this$1`

- renovate.json
Fix description error
`"description": "Ignore node add peerDependencies"`=>`"description": "Ignore node and peerDependencies"`
> fix renovate rule description

- src/index.ts
The `generateDtsFromTs` path expects cases where `!module.source` but since #249 `getModule` does not actually return it as it fails trying to use it for gathering `code`.
> Fix fallback path

- package.json
In our application we use strict dependency license checking.
rollup-plugin-dts has **LGPL-3.0** in license field, but according to [license docs](https://spdx.org/licenses/LGPL-3.0.html), the identifier "**LGPL-3.0**" has been deprecated; **LGPL-3.0-only** is the preferred identifier to indicate only version 3.0 of the LGPL.
Can we change license field value in pacakge.json to **LGPL-3.0-only**?
> chore(copyright): update license to LGPL-3.0-only

- src/transform/preprocess.ts
- tests/testcases/unnamed-default-export-without-space/expected.d.ts
- tests/testcases/unnamed-default-export-without-space/index.d.ts
Currently it throws errors like this:
```ts
[!] (plugin dts) Error: Syntax not yet supported
62 | }
63 |
> 64 | declare functionexport_default<T extends Request = Request>(
| ^^^^^^^
65 |  options?: IOptions<T>
66 | ): Polka<T>;
67 |
node_modules/.pnpm/polka@1.0.0-next.25/node_modules/polka/index.d.mts
at Transformer.convertStatement (file:///Users/divyansh/vitepress/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@4.17.2_typescript@5.4.5/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1301:19)
at new Transformer (file:///Users/divyansh/vitepress/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@4.17.2_typescript@5.4.5/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1230:18)
at convert (file:///Users/divyansh/vitepress/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@ …
```
> fix: don't break transform when there is no space between unnamed default exported function and generic parameter bracket

- .github/workflows/ci.yml
- rollup.config.ts
- src/index.ts
- src/options.ts
- src/program.ts
- src/transform/DeclarationScope.ts
- src/transform/NamespaceFixer.ts
- src/transform/Transformer.ts
- src/transform/astHelpers.ts
- src/transform/errors.ts
- src/transform/index.ts
- src/transform/preprocess.ts
I acknowledge that this project is in maintenance mode, but I think it could still benefit from some minor improvements:
- Use `const` instead of `let` when possible.
- It makes the code more easy to read, plus it can help to avoid potential future bugs.
- Although it can worsen performance for one-time executions, it does the opposite for code that executes a sufficient number of times (which is likely when working on large projects).
- Use `node:*` imports instead of "unqualified" imports for intrinsic modules.
- They have been supported since Node v14.18, which is already marked as not supported.
- These imports can help to avoid potential module naming conflicts and the associated risks.
- Mark types imports as such (available since TS v3.8)
- Use "normal" strings instead of …
> refactor: minor improvements

- src/index.ts
- tests/testcases/using-ts-files/common.ts
The dts plugin runs TypeScript to generate .d.ts files for .ts inputs. This often _just works_. However in some cases it still fails to fetch types from deep dependencies. I used to [turn off all strict type-checking options](https://github.com/hyrious/dts/commit/5cda654e7786767942824f44bfa13e7bdcf7e510#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80) to get rid of these errors, but today I found a special case which doesn't work in any option settings:
```ts
// @ts-expect-error
expectString(null)
function expectString(a: string) {}
```
1. If `strictNullChecks: false`, the code above raises `Unused '@ts-expect-error' directive`.
2. If I remove the directive, the code above cannot pass my projects type checking.
I only want to generate and bundle types and don't want …
> fix: force emit types even when there're errors

- src/transform/NamespaceFixer.ts
- src/transform/Transformer.ts
- tests/testcases/re-export-namespace-inner/expected.d.ts
- tests/testcases/re-export-namespace-inner/index.d.ts
- tests/testcases/re-export-namespace-inner/mod.d.ts
Previously we would generate `declare const …: typeof …` which declares an object with the same value members but none of the type members.
- Fixes #322.
> fix: Preserve type members of namespace in re-exported module

- src/transform/TypeOnlyFixer.ts
- src/transform/index.ts
This commit enables users to remap declaration source maps by passing back the computed difference.
To utilize the original DTS source map, users may need additional plugins like `rollup-sourcemap`.
> fix: Return Source Map Differences to Rollup

- src/transform/Transformer.ts
- src/transform/TypeOnlyFixer.ts
- src/transform/preprocess.ts
- tests/testcases/custom-tsconfig/expected.d.ts
- tests/testcases/type-only-import-export/meta.js
resolves #340
This PR temporarily disables the type-only transform until we find a safer way to handle this issue.
Previously closed issue #311 needs to be reopen, sorry for the inconvenience...
> fix: disable the type-only transform

- src/transform/DeclarationScope.ts
- src/transform/preprocess.ts
- tests/testcases/namespace-child-import/expected.d.ts
- tests/testcases/namespace-child-import/foo.d.ts
- tests/testcases/namespace-child-import/index.d.ts
- tests/testcases/namespace-child-import/meta.js
- tests/testcases/namespace-function-alias/expected.d.ts
- tests/testcases/namespace-function-alias/index.d.ts
- tests/testcases/namespace-function-alias/meta.js
- tests/testcases/namespace-nested-export/expected.d.ts
- tests/testcases/namespace-nested-export/index.d.ts
- tests/testcases/namespace-nested-export/meta.js
- tests/testcases/namespace-nested-export/types.d.ts
- tests/testcases/namespace-nested-shadowing/expected.d.ts
- tests/testcases/namespace-nested-shadowing/index.d.ts
- tests/testcases/namespace-nested-shadowing/meta.js
- tests/testcases/namespace-nested-shadowing/types.d.ts
Added support for `import` alias declarations (e.g. `import Alias = Other.Type`) inside `declare namespace` blocks:
- Update `DeclarationScope` to correctly hoist and resolve references from child imports within a namespace.
- New recursive pre-processing step to correctly handle arbitrarily nested namespaces.
- Refactor of the modifier fixing logic to be context-aware, preventing regressions in `declare module` and `declare global` blocks by applying different rules to top-level vs nested declarations.
Added new tests:
- `namespace-child-import`
This is the foundational "happy path" test. It confirms the most basic requirement: a simple `import =` alias inside a single namespace is correctly rewritten to `type =`.
- `namespace-nested-shadowing`
This is a complex scenario test. It …
> feat(transform): add support for child imports and nesting in namespaces

- src/transform/preprocess.ts
- tests/testcases/namespace-child-import/expected.d.ts
- tests/testcases/namespace-child-import/index.d.ts
- tests/testcases/namespace-function-alias/expected.d.ts
- tests/testcases/namespace-function-alias/index.d.ts
- tests/testcases/namespace-nested-export/expected.d.ts
- tests/testcases/namespace-nested-export/index.d.ts
- tests/testcases/namespace-nested-shadowing/expected.d.ts
- tests/testcases/namespace-nested-shadowing/index.d.ts
- tests/testcases/namespace-reexport-interface/expected.d.ts
- tests/testcases/namespace-reexport-interface/index.d.ts
- tests/testcases/namespace-reexport-interface/types.d.ts
Fixes https://github.com/Swatinem/rollup-plugin-dts/pull/352#issuecomment-3283535379 where import alias declarations inside namespaces were being rewritten as type aliases, changing their meaning.
Previously, `export import Data = ArrayObjectStore.Data` (an `interface`) was converted into a `type` alias, which breaks type identity and confuses tools like IDEs and doc generators. The transformer already handles import equals correctly, so this conversion was unnecessary.
The fix removes the `import` to `type` rewrite in `preProcessNamespaceBody`. Tests for namespace child imports, nested exports, and shadowing now preserve import, and a new case (`namespace-reexport-interface`) confirms interfaces re-export properly.
Thanks @typhonrt for pointing this out and providing a real example.
> fix(transform): preserve `import =` in namespaces
