- tests/testcases/export-all/expected.d.ts
- tests/testcases/export-all/index.d.ts
> test: export all

- src/DeclarationScope.ts
- tests/testcases/spread-tuple-type/expected.d.ts
- tests/testcases/spread-tuple-type/index.ts
> fix(#59): add support for tuple type spread operator

- .gitattributes
- .github/workflows/ci.yml
- .travis.yml
> Use github actions for CI

- src/NamespaceFixer.ts
> fix: should with comma always

- src/DeclarationScope.ts
> Handle new getter accessor typings in TS 3.7

- src/program.ts
Fixes #71 
I'm not sure exactly how to test this. 🤔 The primary way I was able to trigger the type check error (`noImplicitAny`) was by having a third-party library without a packaged `d.ts` file that I wanted to account for with a local declaration. All current tests continue to pass however with these changes.
I added a `Set` to track the found `d.ts` files but that may be overkill — just seemed like the easiest way to prevent duplication in modification to `inputs`. Not sure if TypeScript would have cared or not.
> Add including discovered d.ts files in ts compile mode

- src/NamespaceFixer.ts
- src/Transformer.ts
- src/astHelpers.ts
- src/index.ts
- tests/testcases/decl-module-or-global/expected.d.ts
- tests/testcases/decl-module-or-global/index.ts
> feat: module declaration or global declaration should 1:1 copy

- src/DeclarationScope.ts
> fix: Tuple type prop compatibility for TS 4

- src/index.ts
See discussion in #137. This was really easy. But I'm a bit confused by the use of magic-string in the package—it doesn't seem to actually _do_ anything with the source maps, it just converts the magic string object back to a string and discards the mapping data (if I'm reading it right). Is that code part of a planned future extension, or am I missing something?
> Use transform hook instead of load hook for code transformation

- src/transform/DeclarationScope.ts
- src/transform/Transformer.ts
- tests/testcases/issue-160-global-namespace/expected.d.ts
- tests/testcases/issue-160-global-namespace/index.d.ts
- tests/testcases/issue-160-global-namespace/mod.d.ts
> Support namespaces without a ModuleBlock

- package-lock.json
- src/transform/NamespaceFixer.ts
- src/transform/preprocess.ts
- tests/testcases/issue-166-namespace-rename/a.d.ts
- tests/testcases/issue-166-namespace-rename/b.d.ts
- tests/testcases/issue-166-namespace-rename/expected.d.ts
- tests/testcases/issue-166-namespace-rename/index.d.ts
> Fix broken renaming for exports from namespaces

- tests/testcases/issue-185-hoist-generic-extends/a.d.ts
- tests/testcases/issue-185-hoist-generic-extends/expected.d.ts
- tests/testcases/issue-185-hoist-generic-extends/index.d.ts
Added test of sample provided in issue.
> issue 185 - added test case

- src/index.ts
- src/program.ts
- tests/testcases/custom-tsconfig/expected.d.ts
- tests/testcases/custom-tsconfig/foo.d.ts
- tests/testcases/custom-tsconfig/index.d.ts
- tests/testcases/custom-tsconfig/meta.js
- tests/testcases/custom-tsconfig/tsconfig.build.json
add `options.tsconfig` option to customize `tsconfig.json` path.
to resolve https://github.com/egoist/tsup/issues/791
> feat: support customize tsconfig.json path

- package-lock.json
- package.json
There should be no changes for user
See https://github.com/Rich-Harris/magic-string/blob/master/CHANGELOG.md
> fix(deps): bump magic-string to 0.27, close #239

- src/index.ts
_Other plugins, such as `node-resolve` are known to cause issues._
_The plugin can consume `.ts` and even `.js` files (with `allowJs: true`), but this is known to cause issues._
_The plugin ignores these by default, unless `respectExternal` is set. `@types` can contain hand-crafted code which is known to cause issues._
See https://github.com/mrm007/rollup-plugin-dts-repro.
```
error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["./scripts"]' and 'exclude' paths were '[]'.
```
Looks like the feature introduced in #234 is causing the above error message. Specifically, this line
https://github.com/Swatinem/rollup-plugin-dts/blob/cc8a9a0ec67969f72eb505e26f227cdc77230974/src/index.ts#L140
When `source` is a relative path and the project is part …
> TypeScript errors when used in a monorepo

- src/transform/preprocess.ts
- tests/testcases/issue-254/expected.d.ts
- tests/testcases/issue-254/foo.d.ts
- tests/testcases/issue-254/index.d.ts
> fix enum modifiers

- package-lock.json
- package.json
> chore(deps): update all non-major dependencies

- src/transform/ExportsFixer.ts
- tests/testcases/issue-284/expected.d.ts
- tests/testcases/issue-284/index.d.ts
> fix: treat an exported namespace as a value export

- src/index.ts
I provided a minimal repository for the issues I encountered and included some testing methods. I also explained the cause of the problem in the `README.md` file. You can find detailed information in the repository corresponding to the link below.
https://github.com/NWYLZW/build-multiple-inputs-dts
> fix: unable to find the program when entry points exist intersection dependency

- src/index.ts
- src/options.ts
- tests/testcases/include-external/expected.d.ts
- tests/testcases/include-external/index.d.ts
- tests/testcases/include-external/meta.js
This pr adds an option to include types from a list of specified packages.
> Feat: Add includeExternal option
